import 'server-only'
import type { Stockist } from '@/lib/stockists'

/**
 * The July customer list, as supplied. Names and regions only — there are
 * no street addresses in the source, which is why the importer geocodes
 * the name against a regional hint rather than an address.
 *
 * Kept out of `public/` deliberately: this is a customer list, and it is
 * only reachable through an admin-only route.
 *
 * Generated from data/stockists-july.csv.
 */
export const STOCKISTS_JULY: Stockist[] = [
  { name: "247 Supermarket, Uyo", region: "AKWA IBOM" },
  { name: "2k Supermarket, Abuja", region: "ABUJA" },
  { name: "3D Radiance Pharmacy, Gbagada", region: "MAINLAND" },
  { name: "6 to 9 Supermarket", region: "MAINLAND" },
  { name: "A.A Best", region: "TRADEFAIR" },
  { name: "A.G COSMETICS", region: "TRADEFAIR" },
  { name: "A.S PHILIPS", region: "TRADEFAIR" },
  { name: "ABUCHI", region: "TRADEFAIR" },
  { name: "ACALVIEN", region: "TRADEFAIR" },
  { name: "Ace Mall Bodija, Ibadan", region: "IBADAN" },
  { name: "ADIVIA STORES, LEKKI COUNTY HOME", region: "ISLAND" },
  { name: "Ajoke", region: "INDIVIDUAL" },
  { name: "All time Supermarket 3, Uyo", region: "AKWA IBOM" },
  { name: "All Time Supermarket, Uyo", region: "AKWA IBOM" },
  { name: "Alpha Pet, Benin", region: "BENIN" },
  { name: "Alpha Pharmacy and Stores, Ikeja", region: "MAINLAND" },
  { name: "Amaka Stores, Asaba", region: "ASABA" },
  { name: "AMAKA TIC", region: "TRADEFAIR" },
  { name: "Amambraco Supermarket, Benin", region: "BENIN" },
  { name: "Amechi PH", region: "PH" },
  { name: "ANDREW (AYT COMMERCIAL ENT.)", region: "TRADEFAIR" },
  { name: "Annies Market Place, Asaba", region: "ASABA" },
  { name: "Arinze, Wuse Abuja", region: "ABUJA" },
  { name: "Assorted Super Centre, Yenogoa", region: "" },
  { name: "AT Cosmetics, Owerri", region: "OWERRI" },
  { name: "Awari Supermarket, Benin", region: "BENIN" },
  { name: "Azores Supermarket Kuje, Abuja", region: "" },
  { name: "Babbo Supermarket, Abuja", region: "" },
  { name: "BADMUS", region: "INDIVIDUAL" },
  { name: "Bag It supermarket Admiralty Way, Lekki", region: "" },
  { name: "Beauty Affairs", region: "TRADEFAIR" },
  { name: "Bedrock Mart Bucknor Isolo", region: "MAINLAND" },
  { name: "BEN TRADEFAIR", region: "TRADEFAIR" },
  { name: "Best Buy Supermarket, Kuje", region: "" },
  { name: "Best Choice Enugu", region: "ENUGU" },
  { name: "BETTER DAYS", region: "" },
  { name: "Better Mart Badore", region: "ISLAND" },
  { name: "Bismid", region: "TRADEFAIR" },
  { name: "Blenco Addo", region: "ISLAND" },
  { name: "Blenco Ilasan Lekki", region: "ISLAND" },
  { name: "Blenco Supermarket Abule Egba", region: "MAINLAND" },
  { name: "Blenco Supermarket Ajiwe, Ajah", region: "ISLAND" },
  { name: "Blenco Supermarket Egbeda", region: "MAINLAND" },
  { name: "Blenco Supermarket, Amadiya", region: "" },
  { name: "Blenco Supermarket, Eputu ibeju Lekki", region: "ISLAND" },
  { name: "Blenco Supermarket, Sangotedo", region: "ISLAND" },
  { name: "Bless Shop Supermarket, Abuja", region: "ABUJA" },
  { name: "Blessed Victoria Supermarket, Abuja", region: "" },
  { name: "BMC COSMETICS", region: "" },
  { name: "BRENT MALL WAREHOUSE, IBADAN", region: "IBADAN" },
  { name: "Bright Cosmetics, Abuja", region: "" },
  { name: "Bright Links Cosmetics Hub", region: "" },
  { name: "Buy and Save Bodija, Ibadan", region: "IBADAN" },
  { name: "Buyplus Mall D Line, PH", region: "PH" },
  { name: "C SMART", region: "TRADEFAIR" },
  { name: "Callys Venture Beauty Store, Wuse Market", region: "" },
  { name: "Careforte Pharm VI", region: "ISLAND" },
  { name: "CEC Drug n more pharmacy and beauty, Lekki", region: "ISLAND" },
  { name: "CECI MEGA PLAZA, AKURE", region: "AKURE" },
  { name: "Ceci Supermarket, Ado-Ekiti", region: "" },
  { name: "CEEBECO", region: "" },
  { name: "Centrus Mall, Asaba", region: "ASABA" },
  { name: "CEO'S MART", region: "ISLAND" },
  { name: "CH Cosmetics Wuse Market, Abuja", region: "" },
  { name: "Chidivac Pharmacy & Stores, Abuja", region: "" },
  { name: "Chimex Stores, Wuse Market", region: "" },
  { name: "China sky supermarket, Abuja", region: "" },
  { name: "CHINAZA", region: "INDIVIDUAL" },
  { name: "chinedu", region: "TRADEFAIR" },
  { name: "Chineye", region: "TRADEFAIR" },
  { name: "CHIOMA (ABF OPP.BORNO PLAZA", region: "TRADEFAIR" },
  { name: "chioma (Vizora)", region: "TRADEFAIR" },
  { name: "chisom", region: "INDIVIDUAL" },
  { name: "CHOGWU", region: "TRADEFAIR" },
  { name: "Christ the King Supermarket Uyo", region: "AKWA IBOM" },
  { name: "CHUPPET", region: "" },
  { name: "Chybike", region: "TRADEFAIR" },
  { name: "CIBSON INVESTMENT", region: "TRADEFAIR" },
  { name: "City Star Mart, Oshogbo", region: "" },
  { name: "C-Nature", region: "TRADEFAIR" },
  { name: "COACH SUPERMARKET", region: "" },
  { name: "Coka Pharmacy & Stores, Benin", region: "BENIN" },
  { name: "Coka Pharmacy & Stores, Off Sapele RD", region: "BENIN" },
  { name: "Compra Mart", region: "ISLAND" },
  { name: "Compra Mart, Orchid", region: "ISLAND" },
  { name: "CONTENDER", region: "TRADEFAIR" },
  { name: "Corner Mart, Asaba", region: "ASABA" },
  { name: "Cost Cutters SUpermarket Abuja", region: "ABUJA" },
  { name: "CUSTOMER GIFT", region: "INDIVIDUAL" },
  { name: "Customer_", region: "INDIVIDUAL" },
  { name: "CyMarc International Limited, Wuse Abuja", region: "" },
  { name: "D CHUKS GLOBAL", region: "TRADEFAIR" },
  { name: "D, EMPEROR GRAND MALL", region: "MAINLAND" },
  { name: "Danax Cosmetics, Ibadan", region: "IBADAN" },
  { name: "Day Toner People's Pharmacy, Lekki", region: "" },
  { name: "Daytoner Aja", region: "" },
  { name: "DBANI Supermarket, Bariga", region: "" },
  { name: "De petex Cosmetics, Abuja", region: "" },
  { name: "De Royal Mall, Yenogoa", region: "" },
  { name: "De Samic, Uyo", region: "AKWA IBOM" },
  { name: "Dee Kam Market Place, Ota", region: "MAINLAND" },
  { name: "Delis VI", region: "ISLAND" },
  { name: "Delux Supermarket Sangotedo", region: "ISLAND" },
  { name: "DESTINED", region: "TRADEFAIR" },
  { name: "Destiny Arikpo", region: "MAINLAND" },
  { name: "Destiny Supermarket Owerri", region: "OWERRI" },
  { name: "DFD Pharmacy & Superstore, Lugbe", region: "" },
  { name: "DFK Super Store, Palm Groove", region: "MAINLAND" },
  { name: "DIVINE MERCY", region: "TRADEFAIR" },
  { name: "DON BISHOP (ONYEKA HILLARY)", region: "" },
  { name: "Doris", region: "INDIVIDUAL" },
  { name: "Down Town Shopping Complex, Uyo", region: "AKWA IBOM" },
  { name: "Eagle Success cosmetics, Abuja", region: "" },
  { name: "Ebeano Supermarket Abuja", region: "ABUJA" },
  { name: "Ebeano Supermarket Agungi Branch", region: "ISLAND" },
  { name: "Ebeano Supermarket Chevron Branch", region: "ISLAND" },
  { name: "Ebeano Supermarket Eleganza", region: "ISLAND" },
  { name: "Ebeano Supermarket Lekki", region: "ISLAND" },
  { name: "Ebeano SUpermarket Oniru", region: "ISLAND" },
  { name: "Ebeano Supermarket, Jakande", region: "" },
  { name: "Ebuka T.f", region: "TRADEFAIR" },
  { name: "Eden Cosmetics Wuse Market, Abuja", region: "" },
  { name: "Edichart Shoping Mall", region: "MAINLAND" },
  { name: "Efe", region: "TRADEFAIR" },
  { name: "EFG MART SUPERMARKET, UYO 1", region: "" },
  { name: "EFG MART UYO", region: "" },
  { name: "EJIS OCEAN", region: "TRADEFAIR" },
  { name: "Ekene", region: "TRADEFAIR" },
  { name: "El- Roi super stores, Auja", region: "" },
  { name: "Elixir Supermarket Benin", region: "BENIN" },
  { name: "Ella", region: "TRADEFAIR" },
  { name: "ELSIM", region: "TRADEFAIR" },
  { name: "Emilo Super Market", region: "PH" },
  { name: "EMMANUEL EJEMBA", region: "TRADEFAIR" },
  { name: "Emmatos Super Store, Aboru", region: "MAINLAND" },
  { name: "Emmatos Super Store, Alagbado", region: "MAINLAND" },
  { name: "Emmatos Super Store, Ishashi 3", region: "" },
  { name: "Enascolin Ventures, Benin", region: "BENIN" },
  { name: "Enej Supermarket, Orchid Rd", region: "" },
  { name: "Enumex Cosmetics Calabar", region: "CALABAR" },
  { name: "Essence Needz Eneka PH", region: "PH" },
  { name: "Essence Needz PH", region: "PH" },
  { name: "Essentials by Grandview", region: "MAINLAND" },
  { name: "Esther", region: "INDIVIDUAL" },
  { name: "ET AL FARMS SUPERSTORES, IKEJA", region: "" },
  { name: "Ever Bright Store", region: "ISLAND" },
  { name: "EVERYDAY SUPERMARKET 4040 OWERRI E11", region: "OWERRI" },
  { name: "EVERYDAY SUPERMARKET ABAKALIKI E13", region: "ABAKALIKI" },
  { name: "EVERYDAY SUPERMARKET AWKA E12", region: "AWKA" },
  { name: "EVERYDAY SUPERMARKET CHOBA PH E6", region: "PH" },
  { name: "EVERYDAY SUPERMARKET GRA PH E2", region: "PH" },
  { name: "EVERYDAY SUPERMARKET IKENEGBU OWERRI E4", region: "OWERRI" },
  { name: "EVERYDAY SUPERMARKET IMSU OWERRI E8", region: "OWERRI" },
  { name: "EVERYDAY SUPERMARKET MCC OWERRI E7", region: "OWERRI" },
  { name: "EVERYDAY SUPERMARKET MGBUOBA PH E9", region: "PH" },
  { name: "EVERYDAY SUPERMARKET PETER ODILI", region: "PH" },
  { name: "EVERYDAY SUPERMARKET RUMUIBEKWE E3 PH", region: "PH" },
  { name: "EVERYDAY SUPERMARKET RUMUOLA E1 PH", region: "PH" },
  { name: "EVERYDAY SUPERMARKET SUMMIT ASABA E10", region: "ASABA" },
  { name: "EVERYDAY SUPERMARKET WORLD BANK OWERRI E5", region: "OWERRI" },
  { name: "Exotica Ph", region: "" },
  { name: "Ezinne Aba", region: "INDIVIDUAL" },
  { name: "Family Mart", region: "OWERRI" },
  { name: "Family Wellness Abuja", region: "ABUJA" },
  { name: "Faxx Stores & Trading Ltd, Abuja", region: "ABUJA" },
  { name: "Feebees Retail Services, Oniru", region: "ISLAND" },
  { name: "Fine Look", region: "TRADEFAIR" },
  { name: "Finrel Warehouse, Ibadan", region: "IBADAN" },
  { name: "First Vigeo Supermarket, Akure", region: "" },
  { name: "FOC", region: "INDIVIDUAL" },
  { name: "Foodco Abeokuta", region: "ABEOKUTA" },
  { name: "Foodco Akinolugbade, Abeokuta", region: "ABEOKUTA" },
  { name: "Foodco Asero, Abeokuta", region: "ABEOKUTA" },
  { name: "Foodco Ibadan", region: "IBADAN" },
  { name: "Foodco Ikotun", region: "MAINLAND" },
  { name: "Foodco Ikoyi", region: "ISLAND" },
  { name: "Foodco Jericho Warehouse, Ibadan", region: "IBADAN" },
  { name: "Foodco Lekki", region: "ISLAND" },
  { name: "Foodco Monatan Warehouse, Ibadan", region: "IBADAN" },
  { name: "Foodco Ologuneru Warehouse, Ibadan", region: "IBADAN" },
  { name: "Foodco Ring Road Warehouse, Ibadan", region: "IBADAN" },
  { name: "Foodies Supermarket Jericho, Ibadan", region: "IBADAN" },
  { name: "Ford Mart Benin City", region: "BENIN" },
  { name: "Ford Mart Supermarket Adolor, Benin City", region: "" },
  { name: "Ford Mart Supermarket Supermarket, Isikolor Road, Benin City", region: "" },
  { name: "Freedom Mart Supermarket, Lekki", region: "ISLAND" },
  { name: "Freshshop Supermarket Transekulu, Enugu", region: "" },
  { name: "Gain More Supermarket", region: "OWERRI" },
  { name: "Gbenga", region: "INDIVIDUAL" },
  { name: "General Supermarket Yenogoa", region: "YENOGOA" },
  { name: "Genesis", region: "TRADEFAIR" },
  { name: "Globus Ago", region: "MAINLAND" },
  { name: "Globus Relativity Stores Trade Fair", region: "TRADEFAIR" },
  { name: "Globus supermarket Ajao Estate Lagos", region: "MAINLAND" },
  { name: "Glorisco Supermarket Owerri", region: "" },
  { name: "Go Trading Enterprises Apapa, Lagos", region: "" },
  { name: "Goodies Ikeja", region: "" },
  { name: "Goshen Stores, Abuja", region: "" },
  { name: "GPS Shopping Mall, Benin", region: "" },
  { name: "Grand Product Abuja", region: "ABUJA" },
  { name: "Grand Products Ikeja", region: "MAINLAND" },
  { name: "Grand Products Kano", region: "KANO" },
  { name: "Grand Products VI", region: "ISLAND" },
  { name: "Greeneil Supermarket Lekki", region: "ISLAND" },
  { name: "Greeneil Supermarket Osapa London", region: "ISLAND" },
  { name: "Hangers Supermarket, Uyo", region: "AKWA IBOM" },
  { name: "Hartley Supermarket Ikoyi", region: "ISLAND" },
  { name: "Hartleys Supermarket VI", region: "ISLAND" },
  { name: "Healthrite Pharmacy 2", region: "MAINLAND" },
  { name: "Healthrite Pharmacy Randle", region: "MAINLAND" },
  { name: "Healthrite Pharmacy Tejuosho", region: "MAINLAND" },
  { name: "HEPZIBAH SUPERMARKET, EKET", region: "PH" },
  { name: "Hexcel Supermarket, Benin City", region: "BENIN" },
  { name: "H-medix Abuja", region: "ABUJA" },
  { name: "HyperCity Ogunabali Port Harcourt", region: "PH" },
  { name: "Hypercity Retail Ltd Ikoku, PH", region: "PH" },
  { name: "HyperCity Retail ltd Tombia Road New GRA PH", region: "PH" },
  { name: "Hypercity Retail Ltd, Trans-Amadi Rd, Port Harcourt", region: "PH" },
  { name: "I C WORLD SUPERMARKET GWARINPA, ABUJA", region: "ABUJA" },
  { name: "IFY FABULOUS COSMETICS, ILORIN", region: "ILORIN" },
  { name: "IK P supermarket, Abuja", region: "" },
  { name: "IK Pharmacy and Supermarket, Benin", region: "BENIN" },
  { name: "Ismail", region: "INDIVIDUAL" },
  { name: "J Lush Supermarket, Ojota", region: "" },
  { name: "James Beauty Cosmetics, Abuja", region: "" },
  { name: "James Peter", region: "" },
  { name: "Jane & Juliet Uyo", region: "AKWA IBOM" },
  { name: "Jara Benin", region: "BENIN" },
  { name: "Jara Edlp Benin", region: "BENIN" },
  { name: "Jara Ekiti", region: "EKITI" },
  { name: "Jara Lagos", region: "MAINLAND" },
  { name: "Jara Oyo", region: "IBADAN" },
  { name: "JBO", region: "TRADEFAIR" },
  { name: "Jendol Abule Egba", region: "MAINLAND" },
  { name: "Jendol Central Warehouse, Egbeda", region: "MAINLAND" },
  { name: "Jendol Odonguyan, Ikorodu", region: "MAINLAND" },
  { name: "Jendol Super Store, Ajah Lagos", region: "ISLAND" },
  { name: "Jendol Supermarket Alakuko", region: "MAINLAND" },
  { name: "Jendol Supermarket Igando 2", region: "MAINLAND" },
  { name: "Jendol Supermarket Ikorodu", region: "MAINLAND" },
  { name: "Jendol Supermarket Isheri", region: "MAINLAND" },
  { name: "Jendol SUpermarket Isolo", region: "MAINLAND" },
  { name: "Jendol Supermarket Ojodu", region: "MAINLAND" },
  { name: "Jendol Superstore Egbeda", region: "MAINLAND" },
  { name: "Jendol Superstore Oju Ore", region: "MAINLAND" },
  { name: "Jendol Superstores Ibafo", region: "MAINLAND" },
  { name: "Jendol Superstores Ijede, Ikorodu 3", region: "MAINLAND" },
  { name: "Jendol Superstores Magidun, Ikorodu 4", region: "" },
  { name: "Jendol Superstores, Ipaja", region: "MAINLAND" },
  { name: "Jendol Superstores, Onibukun", region: "MAINLAND" },
  { name: "Jennifer", region: "INDIVIDUAL" },
  { name: "Joeddy Supermarket, Anthony Village", region: "MAINLAND" },
  { name: "JOEPAL SUPERMARKET YENOGOA", region: "YENOGOA" },
  { name: "John Ojo", region: "INDIVIDUAL" },
  { name: "JOVIT MART, UMUAHIA", region: "ABIA" },
  { name: "Joy Ayoleyi", region: "INDIVIDUAL" },
  { name: "JUDE V TRADEFAIR", region: "TRADEFAIR" },
  { name: "Judel Supermarket", region: "AKWA IBOM" },
  { name: "Judith", region: "" },
  { name: "JUSTCOM STORES, OGUDU", region: "MAINLAND" },
  { name: "JUSTRITE CENTRAL WAREHOUSE IKEJA", region: "MAINLAND" },
  { name: "Justrite Supermarket Eleyele, Ibadan", region: "IBADAN" },
  { name: "Justrite Supermarktet Sango Otta", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORE OBANTOKO", region: "ABEOKUTA" },
  { name: "JUSTRITE SUPERSTORE ABEOKUTA", region: "ABEOKUTA" },
  { name: "JUSTRITE SUPERSTORE ABULE EGBA", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORE AKOBO, IBADAN", region: "IBADAN" },
  { name: "Justrite SuperStore Akowonjo Egbeda", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORE AYOBO", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORE CASSO, LAGOS", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORE DOPEMU", region: "MAINLAND" },
  { name: "Justrite Superstore Funaab, Ogun State", region: "" },
  { name: "JUSTRITE SUPERSTORE IGANDO, LAGOS STATE", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORE IJU", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORE IKATE LEKKI", region: "ISLAND" },
  { name: "JUSTRITE SUPERSTORE IKORODU", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORE IKORODU 2", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORE ILE- IFE, OSUN STATE", region: "OSUN" },
  { name: "JUSTRITE SUPERSTORE ISOLO", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORE IYANA IPAJA", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORE KEMTA, OGUN STATE", region: "ABEOKUTA" },
  { name: "JUSTRITE SUPERSTORE LAFENWA, OGUN SATET", region: "ABEOKUTA" },
  { name: "JUSTRITE SUPERSTORE ODONGUYAN, IKORODU 3", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORE OJODU", region: "MAINLAND" },
  { name: "Justrite Superstore Oshogbo", region: "OSUN" },
  { name: "Justrite Superstore Owode", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORE RING ROAD, IBADAN", region: "IBADAN" },
  { name: "JUSTRITE SUPERSTORE, OMOLE", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORES ALAKUKO", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORES BARIGA", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORES EKORO, LAGOS", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORES GOWON ESTATE", region: "MAINLAND" },
  { name: "Justrite Superstores Ibafo Lagos", region: "MAINLAND" },
  { name: "JUSTRITE SUPERSTORES ILESHA", region: "" },
  { name: "Justrite Superstores, Ogba Ikeja", region: "" },
  { name: "jykesweb", region: "TRADEFAIR" },
  { name: "Kanof", region: "TRADEFAIR" },
  { name: "Katta Supermarket", region: "MAINLAND" },
  { name: "Katta Supermarket, AIT Branch", region: "" },
  { name: "Kevs Departmental Stores, Benin", region: "BENIN" },
  { name: "Kls supermarket, Ikeja", region: "ISLAND" },
  { name: "Kodis", region: "TRADEFAIR" },
  { name: "Lapas Mall Ajah", region: "" },
  { name: "LAPAZ MALL LIMITED", region: "ISLAND" },
  { name: "Lead Gate Supermarket Jabi Lake, Abuja", region: "ABUJA" },
  { name: "Lead Supermarket Warehouse, Oshogbo", region: "OSUN" },
  { name: "LEEDEL SUPER STORE", region: "OWERRI" },
  { name: "Leedel Superstore Ikenegbu, Owerri", region: "OWERRI" },
  { name: "LEGEND SUPERMARKET (OPPOSITE HOUSE ON THE ROCK)", region: "" },
  { name: "Li-m Supermarket, Ota", region: "MAINLAND" },
  { name: "Limitless Mart, Eputu", region: "ISLAND" },
  { name: "LMSN Supermarket, Benin", region: "BENIN" },
  { name: "Lozzy Supermarket Yenogua", region: "YENOGOA" },
  { name: "Lython Cosmetics Ekeonuwa, Owerri", region: "OWERRI" },
  { name: "Macmannie Supermarket, Ogba", region: "MAINLAND" },
  { name: "MAC-VISCO LTD", region: "TRADEFAIR" },
  { name: "MADAM CHARLES", region: "TRADEFAIR" },
  { name: "Madam Chinenye", region: "TRADEFAIR" },
  { name: "MADAM CHINWE (ETHEL N ELLA BEAUTY)", region: "TRADEFAIR" },
  { name: "Madam Donella", region: "TRADEFAIR" },
  { name: "MADAM GRACE", region: "TRADEFAIR" },
  { name: "MADAM OLUCHI", region: "TRADEFAIR" },
  { name: "Madam UC", region: "TRADEFAIR" },
  { name: "Madina Lifestyle & Supermarket, Somolu", region: "" },
  { name: "Maldora supermarket , Ifako", region: "" },
  { name: "Mama Tega, Tejuosho Market", region: "MAINLAND" },
  { name: "Mankind Pharmacy and Supermarket, Benin", region: "BENIN" },
  { name: "MARK CHOICE", region: "TRADEFAIR" },
  { name: "Market Square Gwarinpa Abuja", region: "ABUJA" },
  { name: "Market Square Aba", region: "ABA" },
  { name: "Market square Aba 2", region: "ABA" },
  { name: "Market Square Ada George PH", region: "PH" },
  { name: "Market Square Aduwawa Benin 2", region: "BENIN" },
  { name: "Market Square Agip Road, PH", region: "PH" },
  { name: "Market Square Airport Road, Benin 3", region: "BENIN" },
  { name: "Market Square Apo 2 Mall, Apo Round About, Abuja", region: "" },
  { name: "Market Square Asaba", region: "ASABA" },
  { name: "Market Square Asaba Mall, Okpanam Road", region: "" },
  { name: "Market Square Awka", region: "AWKA" },
  { name: "Market Square Benin Sapele Road", region: "BENIN" },
  { name: "Market Square Choba", region: "PH" },
  { name: "Market Square Dawaki District, Abuja", region: "ABUJA" },
  { name: "Market Square Delta Mall", region: "" },
  { name: "Market Square Eket", region: "PH" },
  { name: "MARKET SQUARE ELELENWO PH", region: "PH" },
  { name: "Market Square Eleme, PH", region: "" },
  { name: "Market Square Enugu", region: "ENUGU" },
  { name: "Market Square Festac", region: "MAINLAND" },
  { name: "Market Square Gateway Mall, Abuja", region: "" },
  { name: "Market Square Gbagi, Ibadan", region: "IBADAN" },
  { name: "Market Square GRA Phase 3 PH", region: "PH" },
  { name: "Market Square Gsm Market Maiduguri, Borno", region: "BORNO" },
  { name: "Market Square Ikot Epene", region: "AKWA IBOM" },
  { name: "Market Square Iwofe Road", region: "PH" },
  { name: "Market Square Kaduna", region: "KADUNA" },
  { name: "Market Square Karu, Abuja", region: "ABUJA" },
  { name: "Market Square Kuje, Abuja", region: "ABUJA" },
  { name: "Market Square Lekki, Lagos", region: "ISLAND" },
  { name: "Market square Maryland, Lagos", region: "MAINLAND" },
  { name: "Market square Mile 3, PH", region: "PH" },
  { name: "Market Square Nzimiro, Port Harcourt", region: "PH" },
  { name: "Market Square Okota", region: "MAINLAND" },
  { name: "Market square Okporo Rumudara Ph", region: "PH" },
  { name: "Market Square Onne PH", region: "PH" },
  { name: "Market Square Owerri", region: "OWERRI" },
  { name: "Market Square Owerri Mall", region: "" },
  { name: "Market Square Owode Idiroko Road, Ogun State", region: "MAINLAND" },
  { name: "Market Square Peter Odili PH", region: "PH" },
  { name: "Market Square Rukpokwu AIrport RD PH", region: "PH" },
  { name: "Market Square Rumuibekwe PH", region: "PH" },
  { name: "Market Square Sangotedo, Lagos", region: "" },
  { name: "Market Square Umuahia", region: "ABIA" },
  { name: "MARKET SQUARE UYO", region: "AKWA IBOM" },
  { name: "Market Square Yenogoa", region: "YENOGOA" },
  { name: "Market Square, Gbagada", region: "MAINLAND" },
  { name: "Marvel Nissi Store", region: "ENUGU" },
  { name: "Mary Anu", region: "" },
  { name: "Max Ambi supermarket, Ibeju Lekki", region: "ISLAND" },
  { name: "Maxland Shopping Center", region: "MAINLAND" },
  { name: "MC Awesome Supermarket, Ajah", region: "ISLAND" },
  { name: "Medplus Pharm", region: "ISLAND" },
  { name: "Mega Plaza", region: "ISLAND" },
  { name: "Mega Plaza VI", region: "ISLAND" },
  { name: "Mesdon Int'l Ltd, Abuja", region: "" },
  { name: "Mitch & Good Supermarket, Ikoyi", region: "ISLAND" },
  { name: "MM2 Ekosodine, Benin", region: "BENIN" },
  { name: "MM2 Isihor, Benin", region: "BENIN" },
  { name: "MMIRI TRADEFAIR", region: "TRADEFAIR" },
  { name: "MOPHETH PHARMACY, VI", region: "ISLAND" },
  { name: "More Mart Alakia, Ibadan", region: "IBADAN" },
  { name: "More Mart Olorunsogo, Ibadan", region: "IBADAN" },
  { name: "More Mart Olunde, Ibadan", region: "IBADAN" },
  { name: "Mosh Pharmacy and Supermarket Bodija, Ibadan", region: "" },
  { name: "Mostan Super Stores, Gbagada", region: "MAINLAND" },
  { name: "MOSTEL COSMETICS, ABUJA", region: "" },
  { name: "Mr. Audu", region: "INDIVIDUAL" },
  { name: "Mr. Makuo", region: "INDIVIDUAL" },
  { name: "MR. SEUN", region: "INDIVIDUAL" },
  { name: "Mr. ugoo ABJ", region: "ABUJA" },
  { name: "Multikers Supermarket VI", region: "ISLAND" },
  { name: "Multimac cosmetic store, Abuja", region: "" },
  { name: "Musibau", region: "INDIVIDUAL" },
  { name: "My Groceries 2go", region: "ISLAND" },
  { name: "My Mart, Lekki", region: "ISLAND" },
  { name: "N.K", region: "TRADEFAIR" },
  { name: "NAFDAC OFFICE", region: "INDIVIDUAL" },
  { name: "Naija Medix Pharmacy, Lekki", region: "" },
  { name: "Nao Supermarket, Ado Ekiti", region: "EKITI" },
  { name: "Nao Supermarket, Akure", region: "AKURE" },
  { name: "ND Stores, Kuje", region: "" },
  { name: "Next Cash & Carry PH", region: "PH" },
  { name: "Nick supermarket, Benin", region: "BENIN" },
  { name: "Nomsky", region: "TRADEFAIR" },
  { name: "Nteps Supermarket Uyo", region: "AKWA IBOM" },
  { name: "O.U.K SUPERMARKET, AKURE", region: "AKURE" },
  { name: "Oasis Mart, Yenogoa", region: "" },
  { name: "Obinna Onitsha", region: "" },
  { name: "OBINNA TRADEFAIR", region: "TRADEFAIR" },
  { name: "OBIREAL", region: "" },
  { name: "OBUM TRADEFAIR", region: "" },
  { name: "oga chucks", region: "TRADEFAIR" },
  { name: "Oga Emeka", region: "TRADEFAIR" },
  { name: "Oga Frank", region: "TRADEFAIR" },
  { name: "Oga O.C", region: "TRADEFAIR" },
  { name: "OGA ONYEKA", region: "TRADEFAIR" },
  { name: "Oga Tony", region: "TRADEFAIR" },
  { name: "Oga Vicky (Righteous Gate) Trade fair", region: "TRADEFAIR" },
  { name: "Ojaja More Oshogbo", region: "OSUN" },
  { name: "Ojajamore Supermarket Ile-Ife", region: "OSUN" },
  { name: "Ojajamore Supermarket, Akure", region: "AKURE" },
  { name: "Okoli Supermarket Ikoyi", region: "ISLAND" },
  { name: "Old English Abule Egba", region: "MAINLAND" },
  { name: "Old english Omole Phase", region: "MAINLAND" },
  { name: "Old English Stores GRA", region: "MAINLAND" },
  { name: "Old English Superstores, Ibadan", region: "MAINLAND" },
  { name: "Old English Surulere", region: "MAINLAND" },
  { name: "Oliva Twist Supermarket, Abuja", region: "ABUJA" },
  { name: "Olivia", region: "TRADEFAIR" },
  { name: "Oluchi", region: "TRADEFAIR" },
  { name: "Olukem Supermarket, Akure", region: "" },
  { name: "Omezera Supermarket, Ikeja", region: "" },
  { name: "One Source Mart, Ikeja", region: "MAINLAND" },
  { name: "ONYEKA TRADEFAIR", region: "TRADEFAIR" },
  { name: "ONYEZE COSMETICS, ABUJA", region: "" },
  { name: "OPEN DOOR SUPERMARKET WUSE", region: "" },
  { name: "oramore", region: "TRADEFAIR" },
  { name: "Organic beauty cosmetics, Abuja", region: "" },
  { name: "Outdoor Sales Activities", region: "INDIVIDUAL" },
  { name: "OZEH", region: "TRADEFAIR" },
  { name: "Ozzy Stores Eti Osa", region: "ISLAND" },
  { name: "Ozzy Stores Ilaje", region: "ISLAND" },
  { name: "Ozzy Stores Osapa London", region: "ISLAND" },
  { name: "P.TOM", region: "TRADEFAIR" },
  { name: "Palais de beaute cosmetics", region: "ISLAND" },
  { name: "PALAIS DE BEAUTE COSMETICS, BIG SHOP", region: "ISLAND" },
  { name: "PALAIS DE BEAUTE COSMETICS, SHOP 1", region: "ISLAND" },
  { name: "PALAIS DE BEAUTE COSMETICS, SHOP 2", region: "ISLAND" },
  { name: "PALAIS DE BEAUTE COSMETICS, SHOP 3", region: "ISLAND" },
  { name: "PATCARGO (NONSO)", region: "" },
  { name: "Paxs Pharmacy Onitsha", region: "ONITSHA" },
  { name: "Pay Day Supermarket Oworoshoki, Lagos", region: "" },
  { name: "PENAFORT SUPERMARKET FESTAC", region: "" },
  { name: "PENAFORTE SUPERMARKET, VILLAGE BUS STOP", region: "TRADEFAIR" },
  { name: "Penny Express Ago", region: "" },
  { name: "Pharma Care Pharmacy, Festac", region: "MAINLAND" },
  { name: "Phil Hallmark Benin", region: "BENIN" },
  { name: "Phil Hallmark Benin 2", region: "BENIN" },
  { name: "Phylmart, Agungi", region: "ISLAND" },
  { name: "Pick n Pay Glover", region: "ISLAND" },
  { name: "PICK N PAY VI", region: "ISLAND" },
  { name: "Prestige Superstores Ajuwon, Akute", region: "MAINLAND" },
  { name: "Prestige Superstores Akesan, Igando", region: "MAINLAND" },
  { name: "Prestige Superstores Ishashi", region: "MAINLAND" },
  { name: "Prestige Superstores Iyana Paja", region: "MAINLAND" },
  { name: "Priceless Stores Okigwe Rd, Owerri", region: "OWERRI" },
  { name: "Priceless Stores Orlu Raod, Owerri", region: "OWERRI" },
  { name: "Priceless Stores Youth center layout, Owerri", region: "OWERRI" },
  { name: "PRIME MART BY MORZI", region: "BENIN" },
  { name: "Prime Mart Superstores Cement", region: "MAINLAND" },
  { name: "Prime Mart Superstores Ifo", region: "MAINLAND" },
  { name: "Prime Mart SuperStores Iyana Ishasgi RD Ojo, Lagos", region: "MAINLAND" },
  { name: "Prime Mart Superstores LASU Idimu IBa Rd AKesan Lagos", region: "MAINLAND" },
  { name: "Prime Mart Superstores Singer", region: "MAINLAND" },
  { name: "Prime Mart Superstores, Agbara", region: "" },
  { name: "Prime Mart Superstores, Okoko", region: "MAINLAND" },
  { name: "Prince Ebeano Abuja", region: "ABUJA" },
  { name: "Prince Ebeano Supermarket Ikeja", region: "MAINLAND" },
  { name: "Prince Ebeano Supermarket, Gudu Abuja", region: "ABUJA" },
  { name: "PROMALL, OWERRI", region: "OWERRI" },
  { name: "Pukka Supermarket, Asaba", region: "" },
  { name: "Q Mart Supermarket, Bariga", region: "MAINLAND" },
  { name: "Quick Point Supermarket, Sangotedo", region: "ISLAND" },
  { name: "Qwik Supermarket, Anthony", region: "MAINLAND" },
  { name: "RABBI", region: "" },
  { name: "Radopin Supermarket 1 Ziks Avenue Awka", region: "AWKA" },
  { name: "Radopin Supermarket 2 Aroma Junction Awka", region: "AWKA" },
  { name: "Radopin Supermarket 3 Kwata Junction Awka", region: "AWKA" },
  { name: "Real Care Pharmacy and Supermarket, Benin", region: "BENIN" },
  { name: "Reno Supermarket Iyana School B/S 3", region: "MAINLAND" },
  { name: "Reno Supermarket, Ejigbo 2", region: "MAINLAND" },
  { name: "Reno Supermarket, Ikotun", region: "MAINLAND" },
  { name: "Reno Supermarket, Isheri 4", region: "MAINLAND" },
  { name: "Reno Superstore, Isuti Road", region: "MAINLAND" },
  { name: "Replenish Supermarket Badore", region: "ISLAND" },
  { name: "RICH WAY SUPERMARKET UYO", region: "AKWA IBOM" },
  { name: "Roban Stores Enugu", region: "ENUGU" },
  { name: "Roinuj Supermarket, Lekki", region: "ISLAND" },
  { name: "Royal Prince Supermarket Berger", region: "MAINLAND" },
  { name: "Royal Prince Supermarket Gbagada", region: "MAINLAND" },
  { name: "Safari Hypermarket, Warri", region: "DELTA" },
  { name: "Sahad Cosmetics Abuja", region: "ABUJA" },
  { name: "Samuel", region: "INDIVIDUAL" },
  { name: "Samuel Akozor", region: "INDIVIDUAL" },
  { name: "Samuel Onyekachukwu", region: "INDIVIDUAL" },
  { name: "Save More Market Place", region: "OWERRI" },
  { name: "SFY Superstores, Ibadan", region: "IBADAN" },
  { name: "Shalom Mega Stores", region: "ABEOKUTA" },
  { name: "Shokem Supermarket Ibadan, UI Branch", region: "" },
  { name: "Shokem Supermarket, Ibadan", region: "IBADAN" },
  { name: "Shopper Gate Enugu", region: "ENUGU" },
  { name: "Shoprite Benin Mall", region: "" },
  { name: "shoprite owerri", region: "" },
  { name: "Shoprite SR Abia Mall 35300", region: "" },
  { name: "Shoprite Sr Abuja Gateway 96663", region: "" },
  { name: "Shoprite Sr Adeniran 57617", region: "" },
  { name: "Shoprite SR Akure Mall 93144", region: "" },
  { name: "Shoprite Sr Asaba 85923", region: "" },
  { name: "Shoprite Sr Circle Mall 64808", region: "" },
  { name: "Shoprite Sr Cocoa Mall 37726", region: "" },
  { name: "Shoprite SR Delta Mall 64785", region: "" },
  { name: "Shoprite SR Enugu 56247", region: "" },
  { name: "Shoprite SR Festival Mall 64777", region: "" },
  { name: "Shoprite SR Garden City Mall PH 79380", region: "" },
  { name: "shoprite SR GRAND TOWER", region: "" },
  { name: "Shoprite Sr Ibadan Mall 56255", region: "" },
  { name: "Shoprite SR Ikeja City Mall 53443", region: "" },
  { name: "Shoprite Sr Jabi Lake 64793", region: "" },
  { name: "Shoprite Sr Kaduna Mall 9663", region: "" },
  { name: "Shoprite SR Kwara Mall 56221", region: "" },
  { name: "Shoprite SR Lekki Mall 64751", region: "" },
  { name: "Shoprite Sr Onitsha mall 64769", region: "" },
  { name: "Shoprite Sr Otta Gateway 83311", region: "" },
  { name: "Shoprite SR Park Lane 37734", region: "" },
  { name: "Shoprite Sr Silverbird 38073", region: "" },
  { name: "Shoprite Sr the Palms 44917", region: "" },
  { name: "SIMON'S SUPERSTORES, AGBARA", region: "MAINLAND" },
  { name: "Sino Mart Superstore, Ota", region: "" },
  { name: "SIsters Lounge, Ilorin", region: "ILORIN" },
  { name: "SkyMart", region: "ISLAND" },
  { name: "Smartiemart Mega Stores", region: "MAINLAND" },
  { name: "SOLEX COSMETICS (UMEH)", region: "TRADEFAIR" },
  { name: "Sorfis Supermarket, Sangotedo", region: "ISLAND" },
  { name: "Spar Adeola Odeku, VI", region: "" },
  { name: "Spar Afprint Compound Surulere", region: "" },
  { name: "Spar Calabar Mall, Calabar", region: "" },
  { name: "Spar Central Business District, Abuja", region: "" },
  { name: "Spar Enugu Mall", region: "" },
  { name: "Spar Gwarinpa, Abuja", region: "" },
  { name: "Spar Ikate Lekki", region: "" },
  { name: "Spar Ilupeju, Mushin", region: "" },
  { name: "Spar Opebi Road, Ikeja", region: "" },
  { name: "Spar Port Harcourt", region: "" },
  { name: "Spar Wuse II, Abuja", region: "" },
  { name: "Spar Wuse Zone 5, Abuja", region: "" },
  { name: "SPEEDYON", region: "TRADEFAIR" },
  { name: "Spinneys Supermarket Addo RD", region: "ISLAND" },
  { name: "St David Pharmacy Warehouse", region: "ISLAND" },
  { name: "Staleg Mall, Ado-Ekiti", region: "EKITI" },
  { name: "Staleg Mall, Akure", region: "AKURE" },
  { name: "Staleg Mall, Ibadan", region: "IBADAN" },
  { name: "Stand By", region: "TRADEFAIR" },
  { name: "STANLEY", region: "TRADEFAIR" },
  { name: "Stop 2 Shop Benin", region: "BENIN" },
  { name: "SUNRISE SUPERMARKET, IBADAN", region: "IBADAN" },
  { name: "Super City Supermarket, PH", region: "PH" },
  { name: "SuperSaver Ajao Estate", region: "MAINLAND" },
  { name: "Supersaver Alapere", region: "MAINLAND" },
  { name: "Supersaver Central Warehouse", region: "MAINLAND" },
  { name: "Supersaver Ikosi", region: "MAINLAND" },
  { name: "Supersaver Shangishan Magodo", region: "MAINLAND" },
  { name: "SuperSaver Supermarket Lekki", region: "ISLAND" },
  { name: "Supersaver Supermarket, Lenox Mall Lekki", region: "ISLAND" },
  { name: "SUREPLUS SUPERMARKET YENOGOA", region: "YENOGOA" },
  { name: "T & M Supermarket, Agungi", region: "ISLAND" },
  { name: "T.F WRITE OFF", region: "INDIVIDUAL" },
  { name: "Tagbo", region: "TRADEFAIR" },
  { name: "Temple Hill Ajah", region: "ISLAND" },
  { name: "Temple Hill Festac", region: "MAINLAND" },
  { name: "Temple hill Isolo", region: "MAINLAND" },
  { name: "The Brands Superstores, Pedro", region: "" },
  { name: "The Label Store", region: "MAINLAND" },
  { name: "The Label Store, Kilo", region: "MAINLAND" },
  { name: "The Prince Mega Cosmetics", region: "PH" },
  { name: "Tobeklen Pharmacy & Stores, Abuja", region: "" },
  { name: "Top Outlet Stores, Abuja", region: "" },
  { name: "TOSCO COSMETICS WUSE MARTKET", region: "" },
  { name: "TOWNSQUARE ASABA", region: "ASABA" },
  { name: "Trade fair cash sales", region: "TRADEFAIR" },
  { name: "Trolley Supermarket Wuse II, Abuja", region: "" },
  { name: "TUSH MART LIMITED, AKURE", region: "AKURE" },
  { name: "Twins Faja Supermarket, Ajah", region: "" },
  { name: "Twins Faja Supermarket, Ijanikin", region: "" },
  { name: "Twins Faja Supermarket, Ipaye B/S", region: "" },
  { name: "U B A Supermarket Awoyaya Bus Stop", region: "" },
  { name: "U B A Supermarket, Ogidan", region: "ISLAND" },
  { name: "U B A Supermarket, Orchid", region: "" },
  { name: "Udeme Supermarket, Ikeja", region: "" },
  { name: "UK DAJI", region: "TRADEFAIR" },
  { name: "Unique Superstore, Ede", region: "" },
  { name: "VALMAC ICE NIG LTD", region: "TRADEFAIR" },
  { name: "Value Exchange Superstores, Arepo", region: "" },
  { name: "Value Exchange Superstores, CMD", region: "MAINLAND" },
  { name: "Value Exchange Superstores, Magodo", region: "MAINLAND" },
  { name: "Value Plus Supermarket Uyo", region: "AKWA IBOM" },
  { name: "Valuemart Stores, Ekoro", region: "MAINLAND" },
  { name: "Vanguard Pharmacy, Akobo", region: "IBADAN" },
  { name: "Veritas Value Village Ventures, Ogudu", region: "" },
  { name: "Victor Abah", region: "" },
  { name: "VICTORY CITY SUPERMARKET, ANTHONY", region: "MAINLAND" },
  { name: "VINOFF (Joy)", region: "TRADEFAIR" },
  { name: "Vintage Supermarket, Benin", region: "BENIN" },
  { name: "warehouse", region: "INDIVIDUAL" },
  { name: "Welcome U Supermarket", region: "PH" },
  { name: "WENDY", region: "TRADEFAIR" },
  { name: "Westgate Cosmetics", region: "MAINLAND" },
  { name: "Wide Choice Ada George", region: "PH" },
  { name: "Wide Choice Choba PH", region: "PH" },
  { name: "Wide Choice Iwofe", region: "PH" },
  { name: "Wonder Supermarket, Benin", region: "BENIN" },
  { name: "Zara Stores, Awka", region: "AWKA" },
  { name: "Zara Stores, Onitsha", region: "ONITSHA" },
  { name: "Zetile Supermarket", region: "ISLAND" },
]
